language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3

install:
    # update aptitude
    - sudo apt-get update -y

    # install aptitude packages
    - LDFLAGS=-lm sudo aptitude install -y $(< requirements)

    # install ruby gems
    - bundle install

script:
    # creating and activating virtualenv
    virtualenv -p install/bin/python2.7 --distribute rubythumbor
    source ./rubythumbor/bin/activate

    # install python requirements
    - pip install -r test_requirements.txt --use-mirrors

    # verify both requirements were met
    - INSTALLDIR=$(python -c "import os; import thumbor; print(os.path.dirname(thumbor.__file__))")

    # finally run tests
    - rake spec

